on:
  schedule:
    - cron:  '30 5,17 * * *'
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  rmlocal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: pre-commit
      id: pre_commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit run --all-files
    - name: docker compose build
      id: compose_build
      run: docker compose -p rmlocal -f docker-compose-local.yml build
    - name: docker compose up first attempt
      id: compose_up_first
      run: docker compose -p rmlocal -f docker-compose-local.yml up --wait
      continue-on-error: true
    - name: docker compose up second attempt
      if: ${{ steps.compose_up_first.outcome == 'failure' }}
      id: compose_up_second
      run: docker compose -p rmlocal -f docker-compose-local.yml up --wait
      continue-on-error: true
    - name: Test rmapi direct
      id: test_rmapi
      run: docker compose -p rmlocal -f docker-compose-local.yml up rmapi --wait; docker ps -a; curl http://127.0.0.1:8000/api/v1/enrollment/status/koira
    - name: Test rmapi NGinx
      id: test_rmnginx
      run: docker compose -p rmlocal -f docker-compose-local.yml up rmnginx --wait; docker ps -a; curl -k https://localmaeher.pvarki.fi:4439/api/v1/enrollment/status/koira

  rmdev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: pre-commit
      id: pre_commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit run --all-files
    - name: docker compose build
      id: compose_build
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml build
    - name: docker compose up first attempt
      id: compose_up_first
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml up --wait
      continue-on-error: true
    - name: docker compose up second attempt
      if: ${{ steps.compose_up_first.outcome == 'failure' }}
      id: compose_up_second
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml up --wait
      continue-on-error: true
    - name: Test rmapi direct
      id: test_rmapi
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml up rmapi --wait; docker ps -a; curl http://127.0.0.1:8000/api/v1/enrollment/status/koira
    - name: Test rmapi NGinx
      id: test_rmnginx
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml up rmnginx --wait; docker ps -a; curl -k https://localmaeher.pvarki.fi:4439/api/v1/enrollment/status/koira
