on:
    pull_request:
    push:
      branches-ignore:
        - main
jobs:
  rmlocal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: docker compose build
      id: compose_build
      run: docker compose -p rmlocal -f docker-compose-local.yml build
    - name: docker compose up first attempt
      id: compose_up_first
      run: docker compose -p rmlocal -f docker-compose-local.yml up
      continue-on-error: true
    - name: docker compose up second attempt
      if: ${{ steps.compose_up_first.outcome == 'failure' }}
      id: compose_up_second
      run: docker compose -p rmlocal -f docker-compose-local.yml up
      continue-on-error: true
    - name: docker start rmlocal-rmapi-1
      id: start_rmapi
      run: docker start rmlocal-rmapi-1; sleep 30; docker ps -a
    - name: docker start rmlocal-rmnginx-1
      id: start_rmnginx
      run: docker start rmlocal-rmnginx-1; sleep 10; docker ps -a
    - name: run pytest
      id: run_pytest
      run: cd ./tests; pytest

  rmdev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: docker compose build
      id: compose_build
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml build
    - name: docker compose up first attempt
      id: compose_up_first
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml up
      continue-on-error: true
    - name: docker compose up second attempt
      if: ${{ steps.compose_up_first.outcome == 'failure' }}
      id: compose_up_second
      run: docker compose -p rmdev -f docker-compose-local.yml -f docker-compose-dev.yml up
      continue-on-error: true
    - name: docker start rmdev-rmapi-1
      id: start_rmapi
      run: docker start rmdev-rmapi-1; sleep 30; docker ps -a
    - name: docker start rmdev-rmnginx-1
      id: start_rmnginx
      run: docker start rmdev-rmnginx-1; sleep 10; docker ps -a
    - name: run pytest
      id: run_pytest
      run: cd ./tests; pytest
