on:
    pull_request:
    push:
      branches-ignore:
        - main
jobs:
    rmlocal:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: docker compose -p rmlocal -f docker-compose-local.yml build
      - run: docker compose -p rmlocal -f docker-compose-local.yml up || >&2
      - run: docker compose -p rmlocal -f docker-compose-local.yml up || >&2
      - run: docker start rmlocal-rmapi-1; sleep 30; docker ps -a; curl http://127.0.0.1:8000/api/v1/enrollment/status/koira
      - run: docker start rmlocal-rmnginx-1; docker ps -a; curl -k https://localmaeher.pvarki.fi:4439/api/v1/enrollment/status/koira
