on:
    pull_request:
    push:
      branches-ignore:
        - main
jobs:
    rmlocal:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: docker compose -p rmlocal -f docker-compose-local.yml build
      - run: docker-compose -p rmlocal -f docker-compose-local.yml up
